plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cinejoy.tv'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cinejoy.tv'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.12.2'
}
